name: Backend-CI Test

on:
  pull_request:
    branches: [main]
    paths: [ 'backend/**' ]
    types: ["opened", "synchronize"]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm config set ignore-scripts false
          pnpm i --force
        working-directory: "backend"

      - name: Build
        run: pnpm build
        working-directory: "backend"
